# This Github workflow only builds a Docker image, it will not publish it to the AWS ECR private registry.
name: build-and-push-docker-image
run-name: Build and push docker image for ${{ inputs.BRANCH != '' && inputs.BRANCH || format('PR-{0}-{1}', github.event.client_payload.github.payload.issue.number, github.event.client_payload.pull_request.head.sha) }}

on:
  workflow_dispatch:
    inputs:
      BRANCH:
        type: choice
        options:
          - develop
          - master
        description: Branch to build and push
        default: develop
        required: true

  repository_dispatch:
    types: [ "docker:push-command" ]

env:
  PROD_AWS_ACCOUNT_ID: 780602547172
  DEV_AWS_ACCOUNT_ID: 874822220446
  AWS_REGION: us-east-1
  ECR_REPOSITORY: kinsend-sqs-consumer
  GIT_REF: ${{ inputs.BRANCH != '' && inputs.BRANCH || github.event.client_payload.pull_request.head.sha }}
  IMAGE_REF: ${{ inputs.BRANCH != '' && inputs.BRANCH || format('PR-{0}-{1}', github.event.client_payload.github.payload.issue.number, github.event.client_payload.pull_request.head.sha) }}

# These permissions are required to allow writing comments and reporting check status.
permissions:
  contents: write
  pull-requests: write
  actions: write
  statuses: write
  issues: write
  checks: write

jobs:
  build-docker-image:
    runs-on: ks-linux

    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ env.GIT_REF }}

      - name: Get git commit hash
        uses: pr-mpt/actions-commit-hash@v2
        id: commit

      - name: Configure dynamic variables
        id: vars
        run: |
          # For local dev.
          # GITHUB_OUTPUT=/dev/stdout
          ref=${{ env.GIT_REF }}
          echo "Ref => $ref"
          
          accountId=${{ env.DEV_AWS_ACCOUNT_ID }}
          roleId="dev"
          version=1.0.0-${{ env.IMAGE_REF }}

          if [[ "$ref" == "master" || "$ref" == "main" ]]; then
            accountId=${{ env.PROD_AWS_ACCOUNT_ID }};
            roleId="prod"
            version=1.0.0-master-${{ steps.commit.outputs.short }}
          fi
          if [[ "$ref" == "develop" ]]; then
            # We are not using "version", because for the `develop` branch the version is fixed to just `1.0.0-develop`
            # without a hash to reduce the need for cleaning up old or one-time versions from ECR.
            version=1.0.0-develop-${{ steps.commit.outputs.short }}
          fi

          registry="${accountId}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com"
          repository="${{ env.ECR_REPOSITORY }}"
          image="${registry}/${repository}:${version}"
          
          echo "Account ID: ${accountId}"
          echo "Role: ${roleId}"
          echo "Repository: ${repository}"
          echo "Version: ${version}"
          echo "Image: ${image}"
          
          echo "accountId=$accountId" >> $GITHUB_OUTPUT 
          echo "registry=$registry" >> $GITHUB_OUTPUT
          echo "image=$image" >> $GITHUB_OUTPUT

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ steps.vars.outputs.accountId }}:role/kinsend-${{ steps.vars.outputs.roleId }}
          role-skip-session-tagging: true
          role-duration-seconds: 900

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ steps.vars.outputs.registry }}

      - name: Build the kinsend-be Docker image
        run: |
          docker build -t ${{ steps.vars.outputs.image }} .

      - name: Push the kinsend-be Docker image
        run: |
          docker push ${{ steps.vars.outputs.image }}

      - name: Post Docker clean-up
        if: ${{ always() }}
        run: |
          rm -rf ~/.docker/config.json
          #docker system prune --all --force

      - name: Post job report comment reaction
        uses: peter-evans/create-or-update-comment@v3
        if: ${{ always() && (github.event.client_payload.slash_command.command != '') }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reactions: ${{ job.status == 'success' && 'hooray' || '-1' }}

      - name: Post job report comment failure
        uses: peter-evans/create-or-update-comment@v3
        if: ${{ failure() && (github.event.client_payload.slash_command.command != '') }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reactions: ${{ job.status == 'success' && 'hooray' || '-1' }}
          body: |
            > 🔴 Failed to push image. For more details check the [build log](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}).

      - name: Post job report add comment on success push
        uses: peter-evans/create-or-update-comment@v3
        if: ${{ success() && (github.event.client_payload.slash_command.command != '') }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
          body: |
            #### Status
            
            🟢 Docker image `${{ steps.vars.outputs.image }}` was successfully pushed.
            
            #### Build log
            
            For more details check the [build log](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}).            

            #### Test
            
            1. Authenticate via `docker login ${{ steps.vars.outputs.registry }}`
            2. Execute the following to test the image:
               ```
               docker run -it --rm ${{ steps.vars.outputs.image }}
               ```
