# This Github workflow only builds a Docker image, it will not publish it to the AWS ECR private registry.
name: build-and-push-docker-image
run-name: Build and push docker image for ${{ inputs.BRANCH != '' && inputs.BRANCH || format('PR-{0}', github.event.client_payload.github.payload.issue.number) }}

on:
  workflow_dispatch:
    inputs:
      BRANCH:
        type: choice
        options:
          - develop
          - master
        description: Branch to build and push
        default: develop
        required: true

  repository_dispatch:
    types: [ "docker:push-command", "ec2:deploy-command" ]

env:
  PROD_AWS_ACCOUNT_ID: 780602547172
  DEV_AWS_ACCOUNT_ID: 874822220446
  AWS_REGION: us-east-1
  ECR_REPOSITORY: kinsend-sqs-consumer
  GIT_REF: ${{ inputs.BRANCH != '' && inputs.BRANCH || github.event.client_payload.pull_request.head.sha }}
  IMAGE_REF: ${{ inputs.BRANCH != '' && inputs.BRANCH || format('PR-{0}', github.event.client_payload.github.payload.issue.number) }}

# These permissions are required to allow writing comments and reporting check status.
permissions:
  contents: write
  pull-requests: write
  actions: write
  statuses: write
  issues: write
  checks: write

jobs:
  build-docker-image:
    runs-on: ks-linux

    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ env.GIT_REF }}

      - name: Get git commit hash
        id: commit
        run: |
          short_sha=$(git rev-parse --short HEAD)
          echo "Short sha is: ${short_sha}"
          echo "short=$short_sha" >> $GITHUB_OUTPUT

      - name: Configure dynamic variables
        id: vars
        run: |
          # For local dev.
          # GITHUB_OUTPUT=/dev/stdout
          ref=${{ env.GIT_REF }}
          echo "Ref => $ref"
          
          accountId=${{ env.DEV_AWS_ACCOUNT_ID }}
          roleId="dev"
          version=1.0.0-${{ env.IMAGE_REF }}
          manifestVersion=$version-${{ steps.commit.outputs.short }}

          if [[ "$ref" == "master" || "$ref" == "main" ]]; then
            accountId=${{ env.PROD_AWS_ACCOUNT_ID }};
            roleId="prod"
            version=1.0.0-master-${{ steps.commit.outputs.short }}
            manifestVersion=$version
          elif [[ "$ref" == "develop" ]]; then
            # We are not using "version", because for the `develop` branch the version is fixed to just `1.0.0-develop`
            # without a hash to reduce the need for cleaning up old or one-time versions from ECR.
            version=1.0.0-develop-${{ steps.commit.outputs.short }}
            manifestVersion=$version
          fi

          registry="${accountId}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com"
          repository="${{ env.ECR_REPOSITORY }}"
          image="${registry}/${repository}:${version}"
          
          echo "Account ID: ${accountId}"
          echo "Role: ${roleId}"
          echo "Repository: ${repository}"
          echo "Version: ${version}"
          echo "Manifest version: ${manifestVersion}"
          echo "Image: ${image}"
          
          echo "accountId=$accountId" >> $GITHUB_OUTPUT 
          echo "roleId=$roleId" >> $GITHUB_OUTPUT 
          echo "registry=$registry" >> $GITHUB_OUTPUT
          echo "version=$version" >> $GITHUB_OUTPUT
          echo "manifestVersion=$manifestVersion" >> $GITHUB_OUTPUT
          echo "image=$image" >> $GITHUB_OUTPUT

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ steps.vars.outputs.accountId }}:role/kinsend-${{ steps.vars.outputs.roleId }}
          role-skip-session-tagging: true
          role-duration-seconds: 900

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ steps.vars.outputs.registry }}

      - name: Build ${{ steps.vars.outputs.image }}
        run: |
          docker build --no-cache --build-arg "MANIFEST_VERSION=${{ steps.vars.outputs.manifestVersion }}" -t ${{ steps.vars.outputs.image }} .

      - name: Push ${{ steps.vars.outputs.image }}
        run: |
          docker push ${{ steps.vars.outputs.image }}

      - name: Deploy SQS consumer to EC2 developer cluster (on demand)
        if: ${{ env.GIT_REF == 'develop' || github.event.client_payload.slash_command.command == 'ec2:deploy' }}
        id: deployment
        run: |
          # For easier development
          if [[ -z $GITHUB_OUTPUT ]]; then
            GITHUB_OUTPUT=/dev/stdout
          fi

          GH_VER='${{ steps.vars.outputs.version }}'
          VERSION=${1:-$GH_VER} # for local dev - the first argument to the script will become the version.

          set -exuo pipefail;

          echo "Preparing to deploy new version: $VERSION" > /dev/null

          echo "Print currently deployed sqs image version" > /dev/null
          aws ssm get-parameter --name dev.kinsend.sqs.image_version

          echo "Update sqs version parameter to $VERSION" > /dev/null
          aws ssm put-parameter --overwrite --type String --name dev.kinsend.sqs.image_version --value $VERSION

          echo "Scale EC2 instance down" > /dev/null
          scalingGroup=$(aws autoscaling describe-auto-scaling-groups | jq -er '.AutoScalingGroups | .[] | select(.AutoScalingGroupName | startswith("kinsend-sqs-agent-")) | .AutoScalingGroupName')
          aws autoscaling update-auto-scaling-group --auto-scaling-group-name $scalingGroup --min-size 0 --desired-capacity 0

          echo "Waiting..." > /dev/null
          sleep 15

          echo "Scaling EC2 instance up" > /dev/null
          aws autoscaling update-auto-scaling-group --auto-scaling-group-name $scalingGroup --min-size 0 --desired-capacity 1

          echo "Waiting for EC2 instance to boot." > /dev/null
          i="0"
          while true; do

            if [[ $i -gt 15 ]]; then
              echo "Error -- EC2 instance did not boot! Manual intervention is required."
              exit 1
            fi

            rawState=$(aws ec2 describe-instances --query 'Reservations[*].Instances[*].[InstanceId,IamInstanceProfile,State]' --filters Name=instance-state-name,Values=running Name=tag:aws:autoscaling:groupName,Values=$scalingGroup | jq -r '.[] | .[]')
            state=$(echo "$rawState" | jq -r '.[2].Name')
            instanceId=$(echo "$rawState" | jq -r '.[0]')

            if [[ "$state" == "running" ]]; then
              echo "instanceId=$instanceId" >> $GITHUB_OUTPUT
              break;
            fi

            echo "No running EC2 instance found. Waiting 30 seconds." > /dev/null
            sleep 30
            i=$((i + 1))
          done

      - name: Post Docker clean-up
        if: ${{ always() }}
        run: |
          rm -rf ~/.docker/config.json
          #docker system prune --all --force

      - name: Post job report comment reaction
        uses: peter-evans/create-or-update-comment@v3
        if: ${{ always() && (github.event.client_payload.slash_command.command != '') }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reactions: ${{ job.status == 'success' && 'hooray' || '-1' }}

      - name: Post job report comment failure
        uses: peter-evans/create-or-update-comment@v3
        if: ${{ failure() && (github.event.client_payload.slash_command.command != '') }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reactions: ${{ job.status == 'success' && 'hooray' || '-1' }}
          body: |
            > 🔴 Failed to push image. For more details check the [build log](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}).

      - name: Post job report add comment on success push
        uses: peter-evans/create-or-update-comment@v3
        if: ${{ success() && (github.event.client_payload.slash_command.command != '') }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
          body: |
            #### Status
            
            🟢 Docker image `${{ steps.vars.outputs.image }}` was successfully pushed.
            ${{ github.event.client_payload.slash_command.command == 'ec2:deploy' && format('🟢 Image `{0}` was deployed to a new EC2  instance', steps.vars.outputs.image) || '🔵 Image deployment was skipped.' }}  

            #### Build log
            
            For more details check the [build log](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}).            

            #### Test 
            
            1. Authenticate via `docker login ${{ steps.vars.outputs.registry }}`

            2. Execute the following to test the image locally:
               ```
               docker run -it --rm ${{ steps.vars.outputs.image }}
               ```

            3. [Check instance via the management console](https://${{ env.AWS_REGION }}.console.aws.amazon.com/ec2/home?region=${{ env.AWS_REGION }}#InstanceDetails:instanceId=${{ steps.deployment.outputs.instanceId }}) (if image was deployed)  
               Note: It takes between 2 to 5 minutes for the new EC2 instance to boot the new docker container. Be patient.
